
# example below, maybe implement as well!?


#name: Release on PYPI
#on:
#  push:
#    branches:  [main]
#
#
#jobs:
#  build-and-publish:
#    runs-on: ubuntu-latest
#    if: github.repository == 'bnzk/django-painless-redirects'
#    steps:
#    - name: Checkout
#      uses: actions/checkout@v2
#    - name: Set up Python
#      uses: actions/setup-python@v2
#    - name: Install build dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install --upgrade setuptools wheel twine
#    - name: Build
#      run: |
#        python setup.py sdist
#        python setup.py bdist_wheel --universal
#    - name: Publish
#      env:
#        TWINE_USERNAME: ${{ secrets.PYPI_USER_BNZK }}
#        TWINE_PASSWORD: ${{ secrets.PYPI_PW_BNZK }}
#      run: twine upload dist/*
